// Disasters dataset for Student Dashboard (Do’s & Don’ts)
// Structure per requirements: id, title, description, dos[], donts[]

export const disastersData = [
  {
    id: 'earthquake',
    title: 'Earthquake Safety',
    description: 'Learn how to stay safe during earthquakes.',
    dos: [
      'Drop, Cover, and Hold On under sturdy furniture.',
      'Stay indoors until shaking stops.',
      'Move away from windows, mirrors, and heavy objects.',
      'Protect your head and neck with your arms.',
      'If outdoors, move to an open area away from buildings and power lines.',
      'If driving, stop safely away from bridges and tunnels.',
      'Keep emergency supplies ready (water, food, flashlight).',
      'Follow evacuation instructions after shaking ends.',
      'Help injured people if safe to do so.',
      'Expect aftershocks and be cautious.',
    ],
    donts: [
      'Don’t run outside during shaking.',
      'Don’t use elevators.',
      'Don’t stand near glass or tall shelves.',
      'Don’t light matches or candles (gas leaks possible).',
      'Don’t overcrowd staircases when evacuating.',
      'Don’t spread rumors or panic.',
      'Don’t ignore official alerts.',
      'Don’t leave heavy objects unsecured at home.',
      'Don’t use damaged buildings after the quake.',
      'Don’t block emergency exits.',
    ],
    quiz: { title: 'Earthquake Quiz', href: '#' },
    drills: { title: 'Earthquake Drill', href: '#' },
  },
  {
    id: 'flood',
    title: 'Flood Preparedness',
    description: 'How to act before, during, and after floods.',
    dos: [
      'Move to higher ground immediately.',
      'Listen to emergency alerts.',
      'Keep drinking water safe.',
      'Turn off electricity before leaving.',
      'Carry emergency supplies.',
      'Stay away from floodwaters.',
      'Help vulnerable people.',
      'Store valuables in waterproof bags.',
      'Keep livestock safe.',
      'Practice family evacuation plan.',
    ],
    donts: [
      'Don’t walk or swim in floodwater.',
      'Don’t drive in flooded areas.',
      'Don’t touch electrical equipment in water.',
      'Don’t drink contaminated water.',
      'Don’t block drainage systems.',
      'Don’t spread rumors.',
      'Don’t go near collapsed bridges.',
      'Don’t return home until safe.',
      'Don’t ignore official warnings.',
      'Don’t panic or delay evacuation.',
    ],
    quiz: { title: 'Flood Quiz', href: '#' },
    drills: { title: 'Flood Drill', href: '#' },
  },
  {
    id: 'wildfire',
    title: 'Wildfire Safety',
    description: 'Protect yourself and others during wildfires.',
    dos: [
      'Evacuate immediately when told.',
      'Keep emergency kit and masks ready.',
      'Wet cloth to cover nose and mouth.',
      'Wear fire-resistant or cotton clothes.',
      'Keep vehicles fueled for evacuation.',
      'Follow official evacuation routes.',
      'Stay indoors if fire is far but air quality is poor.',
      'Remove dry leaves/combustibles from surroundings.',
      'Help neighbors in need.',
      'Report new fires to authorities.',
    ],
    donts: [
      'Don’t stay behind to protect property.',
      'Don’t re-enter burned areas.',
      'Don’t light outdoor fires during dry seasons.',
      'Don’t use elevators during evacuation.',
      'Don’t block evacuation roads.',
      'Don’t breathe smoke directly.',
      'Don’t spread unverified information.',
      'Don’t waste time gathering belongings.',
      'Don’t leave pets behind.',
      'Don’t ignore fire alarms or alerts.',
    ],
    quiz: { title: 'Wildfire Quiz', href: '#' },
    drills: { title: 'Wildfire Drill', href: '#' },
  },
  {
    id: 'hurricane',
    title: 'Hurricane / Cyclone',
    description: 'Prepare for and stay safe during hurricanes or cyclones.',
    dos: [
      'Stay indoors during the storm.',
      'Board up windows and doors.',
      'Keep emergency kit ready.',
      'Charge all electronic devices.',
      'Follow evacuation orders.',
      'Move to higher ground in case of flooding.',
      'Stay tuned to official updates.',
      'Secure outdoor items (furniture, plants).',
      'Store drinking water safely.',
      'Help neighbors, especially elderly.',
    ],
    donts: [
      'Don’t go outside during the eye of the storm.',
      'Don’t ignore evacuation orders.',
      'Don’t use candles (fire hazard).',
      'Don’t drive in flooded areas.',
      'Don’t leave pets unattended.',
      'Don’t spread panic.',
      'Don’t rely on rumors or social media only.',
      'Don’t swim in stormy seas.',
      'Don’t return until safe.',
      'Don’t use contaminated water.',
    ],
    quiz: { title: 'Hurricane Quiz', href: '#'},
    drills: { title: 'Hurricane Drill', href: '#'},
  },
  {
    id: 'tsunami',
    title: 'Tsunami Preparedness',
    description: 'Be ready for coastal tsunamis.',
    dos: [
      'Move to higher ground immediately after shaking.',
      'Listen to tsunami warnings and alerts.',
      'Follow official evacuation routes.',
      'Carry emergency supplies.',
      'Help children and elderly during evacuation.',
      'Stay away from coastal areas until declared safe.',
      'Keep important documents in waterproof bags.',
      'Practice tsunami evacuation drills.',
      'Stay tuned to official updates.',
      'Stay calm and assist others.',
    ],
    donts: [
      'Don’t wait to see the waves.',
      'Don’t go back to shore until cleared.',
      'Don’t spread rumors or panic.',
      'Don’t swim in strong currents.',
      'Don’t block evacuation paths.',
      'Don’t underestimate small tremors near the coast.',
      'Don’t stay in low-lying areas.',
      'Don’t use vehicles if roads are jammed.',
      'Don’t drink flood-contaminated water.',
      'Don’t ignore repeated warnings.',
    ],
    quiz: { title: 'Tsunami Quiz', href: '#'},
    drills: { title: 'Tsunami Drill', href: '#'},
  },
  {
    id: 'pandemic',
    title: 'Pandemic Safety',
    description: 'Stay healthy during widespread disease outbreaks.',
    dos: [
      'Wash hands regularly',
      'Wear masks in crowded places',
      'Follow health guidelines',
    ],
    donts: [
      'Don’t ignore symptoms',
      'Don’t spread misinformation',
      'Don’t neglect vaccination',
    ],
    quiz: { title: 'Pandemic Quiz', href: '#'},
    drills: { title: 'Pandemic Drill', href: '#'},
  },
  {
    id: 'heatwave',
    title: 'Heatwave Readiness',
    description: 'Stay cool and safe during extreme heat.',
    dos: [
      'Drink plenty of water',
      'Stay in the shade or indoors',
      'Wear light clothing',
    ],
    donts: [
      'Don’t leave kids or pets in cars',
      'Don’t overexert during peak heat',
      'Don’t ignore signs of heatstroke',
    ],
    quiz: { title: 'Heatwave Quiz', href: '#'},
    drills: { title: 'Heatwave Drill', href: '#'},
  },
  {
    id: 'landslide',
    title: 'Landslide Awareness',
    description: 'Know what to do in landslide-prone areas.',
    dos: [
      'Stay alert in hilly/rain-prone areas.',
      'Move away from landslide paths quickly.',
      'Follow official evacuation orders.',
      'Keep emergency kit ready.',
      'Report early warning signs (cracks, tilting trees).',
      'Stay tuned to weather reports.',
      'Help others evacuate.',
      'Keep drainage systems clear.',
      'Carry important documents in waterproof bags.',
      'Move to safe zones immediately.',
    ],
    donts: [
      'Don’t build houses near steep slopes.',
      'Don’t ignore warning signs.',
      'Don’t return until declared safe.',
      'Don’t block natural water flow.',
      'Don’t walk near riverbanks during heavy rain.',
      'Don’t park vehicles near slopes.',
      'Don’t underestimate small landslides.',
      'Don’t spread panic.',
      'Don’t neglect community evacuation plans.',
      'Don’t stay inside unstable buildings.',
    ],
    quiz: { title: 'Landslide Quiz', href: '#'},
    drills: { title: 'Landslide Drill', href: '#'},
  },
  {
    id: 'volcano',
    title: 'Volcano Safety',
    description: 'Protect yourself from volcanic ash and hazards.',
    dos: [
      'Stay indoors to avoid ash.',
      'Use masks or cloth to cover your nose and mouth.',
      'Keep windows and doors closed.',
      'Follow official evacuation orders.',
      'Wear long-sleeved clothing to protect skin.',
      'Stay tuned to radio or official updates.',
      'Prepare emergency kits with goggles and water.',
      'Keep vehicles indoors to avoid ash damage.',
      'Help vulnerable people (elderly, kids).',
      'Stay away from rivers (can carry lava or ash).',
    ],
    donts: [
      'Don’t go near lava flows or craters.',
      'Don’t breathe volcanic ash directly.',
      'Don’t drive unless absolutely necessary.',
      'Don’t ignore evacuation instructions.',
      'Don’t drink ash-contaminated water.',
      'Don’t panic or rush evacuation.',
      'Don’t leave pets behind.',
      'Don’t use contact lenses (ash irritation).',
      'Don’t stand on rooftops with heavy ash (collapse risk).',
      'Don’t spread unverified information.',
    ],
    quiz: { title: 'Volcano Quiz', href: '#'},
    drills: { title: 'Volcano Drill', href: '#'},
  },
  {
    id: 'tornado',
    title: 'Tornado Safety',
    description: 'Know where to shelter and how to stay safe during tornadoes.',
    dos: [
      'Go to a basement or storm shelter.',
      'Stay in an interior room with no windows.',
      'Protect your head with arms or a helmet.',
      'Keep a radio for weather alerts.',
      'Cover yourself with blankets or a mattress.',
      'Stay away from doors and windows.',
      'If outdoors, find a low ditch or depression.',
      'Keep emergency supplies ready.',
      'Secure heavy objects at home.',
      'Practice tornado drills with family.',
    ],
    donts: [
      'Don’t stay in mobile homes.',
      'Don’t try to outrun a tornado in a car.',
      'Don’t open windows to “equalize pressure.”',
      'Don’t stand near glass or doors.',
      'Don’t ignore sirens or warnings.',
      'Don’t use elevators.',
      'Don’t waste time collecting belongings.',
      'Don’t take shelter under bridges.',
      'Don’t go outside to “watch” the tornado.',
      'Don’t panic—stay low and covered.',
    ],
    quiz: { title: 'Tornado Quiz', href: '#'},
    drills: { title: 'Tornado Drill', href: '#'},
  },
  {
    id: 'drought',
    title: 'Drought Preparedness',
    description: 'Conserve water and adapt during droughts.',
    dos: [
      'Conserve water daily.',
      'Collect rainwater if possible.',
      'Grow drought-resistant plants.',
      'Take shorter showers.',
      'Use water-efficient appliances.',
      'Reuse greywater for plants.',
      'Educate community on water conservation.',
      'Store drinking water in clean containers.',
      'Support reforestation efforts.',
      'Follow government water usage rules.',
    ],
    donts: [
      'Don’t waste water unnecessarily.',
      'Don’t wash vehicles frequently.',
      'Don’t over-irrigate fields.',
      'Don’t leave taps running.',
      'Don’t ignore leaks at home.',
      'Don’t use drinking water for non-essential tasks.',
      'Don’t pollute available water sources.',
      'Don’t panic-buy bottled water.',
      'Don’t cut down trees.',
      'Don’t ignore official restrictions.',
    ],
    quiz: { title: 'Drought Quiz', href: '#'},
    drills: { title: 'Drought Drill', href: '#'},
  },
];

export default disastersData;
