// Disasters dataset for Student Dashboard (Do’s & Don’ts)
// Structure per requirements: id, title, description, dos[], donts[]

export const disastersData = [
  {
    id: 'earthquake',
  title: 'Earthquake',
    description: 'Learn how to stay safe during earthquakes.',
    plan: [
      'Repair deep plaster cracks in ceilings and foundations with expert advice.',
      'Anchor overhead lighting fixtures and ceiling fans.',
      'Follow BIS building codes relevant to earthquake-prone zones.',
      'Fasten shelves securely to walls.',
      'Store heavy items on lower shelves.',
      'Keep glassware, china, and bottles in closed cabinets with latches.',
      'Hang heavy mirrors and frames away from beds and seating areas.',
      'Brace overhead lights, chandeliers, and fans.',
      'Repair faulty wiring and leaky gas connections immediately.',
      'Strap water heaters, LPG cylinders to walls and floors.',
      'Store flammable products (weed killers, pesticides) in secure cabinets.',
      'Identify safe indoor spots (under strong furniture, against inside walls).',
      'Identify safe outdoor spots (open ground away from buildings and trees).',
      'Educate family members on Drop, Cover, Hold techniques.',
      'Practice earthquake drills regularly.',
      'Prepare a go-bag with food, water, and torchlight.',
      'Learn emergency phone numbers by heart.',
      'Ensure schools and institutions follow seismic safety codes.',
      'Keep first-aid kits ready and accessible.',
    ],
    recovery: [
      'Ensure safety first – check yourself and family for injuries.',
      'Move to open areas; avoid damaged buildings.',
      'Switch off gas, water, and electricity to prevent fire or leaks.',
      'Listen to official advisories on aftershocks.',
      'Inspect home for cracks and unsafe structures.',
      'Clean up broken glass, spilled chemicals, or debris carefully.',
      'Seek temporary shelter if your home is unsafe.',
      'Rebuild with earthquake-resistant designs.',
    ],
    effects: [
      'Loss of human lives and serious injuries',
      'Collapse of buildings, bridges, and roads',
      'Fires from broken gas and electrical lines',
      'Disruption of transport and communication',
      'Triggering of landslides and tsunamis',
      'Shortage of food, water, and shelter',
      'Economic losses from damaged industries and businesses',
      'Long-term trauma and mental health impacts',
    ],
    know: [
      'Sudden shaking or rolling of the Earth’s surface.',
      'Caused by movement of rocks along fault lines.',
      'Can last from a few seconds to a minute.',
      'Felt over large areas, even if the center is small.',
      'Strength is measured on the Richter Scale.',
      'Can damage buildings, roads, and bridges.',
      'May trigger landslides or tsunamis.',
      'Aftershocks may follow the main quake.',
      'Cannot be predicted accurately.',
      'Drop, Cover, and Hold On is the key safety action.',
      // Extra details
      'Earthquakes often occur near tectonic plate boundaries.',
      'The Richter scale measures earthquake magnitude.',
      'The Mercalli scale measures earthquake intensity based on effects.',
      'Aftershocks can follow a major quake, sometimes for weeks.',
      'Earthquakes can trigger landslides and tsunamis.',
      'Soft soil areas tend to amplify shaking.',
      'Liquefaction can cause the ground to behave like liquid.',
      'Most earthquakes last less than 30 seconds.',
      'Seismic waves travel at different speeds through Earth’s crust.',
      'Underground water pipelines and gas lines are highly vulnerable.',
    ],
    dos: [
      'Drop, Cover, and Hold On under sturdy furniture.',
      'Stay indoors until shaking stops.',
      'Move away from windows, mirrors, and heavy objects.',
      'Protect your head and neck with your arms.',
      'If outdoors, move to an open area away from buildings and power lines.',
      'If driving, stop safely away from bridges and tunnels.',
      'Keep emergency supplies ready (water, food, flashlight).',
      'Follow evacuation instructions after shaking ends.',
      'Help injured people if safe to do so.',
      'Expect aftershocks and be cautious.',
    ],
    donts: [
      'Don’t run outside during shaking.',
      'Don’t use elevators.',
      'Don’t stand near glass or tall shelves.',
      'Don’t light matches or candles (gas leaks possible).',
      'Don’t overcrowd staircases when evacuating.',
      'Don’t spread rumors or panic.',
      'Don’t ignore official alerts.',
      'Don’t leave heavy objects unsecured at home.',
      'Don’t use damaged buildings after the quake.',
      'Don’t block emergency exits.',
    ],
    quiz: { title: 'Earthquake Quiz', href: '#' },
    drills: { title: 'Earthquake Drill', href: '#' },
  },
  {
    id: 'flood',
  title: 'Flood',
    description: 'How to act before, during, and after floods.',
    plan: [
      'Educate family and neighbors on flood risks.',
      'Create a family flood emergency plan.',
      'Identify flood paths and likely inundation areas.',
      'Inspect and clear escape routes.',
      'Strengthen home entry points with tarps/sandbags.',
      'Agree on a family meeting point outside flood zone.',
      'Share a common emergency contact number (out-of-area friend).',
      'Prepare a list of emergency phone numbers.',
      'Keep copies of IDs and important documents waterproofed.',
      'Raise electrical switches above flood levels.',
      'Store food, water, and medicine in waterproof containers.',
      'Learn how to shut off electricity, water, and gas.',
      'Keep livestock and pets safe at higher ground.',
      'Monitor radio/TV for warnings.',
      'Keep boats/rafts handy in flood-prone zones.',
      'Never drive across flooded roads.',
      'Teach children not to play in floodwater.',
      'Prepare evacuation bags with essentials.',
      'Plan safe return only after official clearance.',
    ],
    recovery: [
      'Return home only when authorities declare it safe.',
      'Avoid wading in floodwater (risk of infection, electricity, or sharp objects).',
      'Clean and disinfect everything touched by floodwater.',
      'Boil or treat drinking water until supply is safe.',
      'Repair damaged sanitation and drainage systems.',
      'Document property damage for insurance or government aid.',
      'Replant crops and restore farmland with soil treatments.',
      'Build raised housing or flood barriers for future protection.',
    ],
    effects: [
      'Drowning and loss of human and animal lives',
      'Waterborne diseases (cholera, diarrhea, malaria)',
      'Destruction of homes, schools, and hospitals',
      'Loss of crops, livestock, and farmlands',
      'Damage to roads, railways, and bridges',
      'Displacement of large populations',
      'Contamination of drinking water sources',
      'Economic losses from halted trade and industries',
      'Breakdown of essential services (power, communication)',
    ],
    know: [
      'Overflow of water submerging normally dry land.',
      'Caused by heavy rain, river overflow, or dam break.',
      'Monsoons bring frequent floods in India.',
      'Low-lying areas are most at risk.',
      'Flash floods happen suddenly with no warning.',
      'Contaminates drinking water sources.',
      'Damages homes, crops, and roads.',
      'May lead to water-borne diseases.',
      'Embankments and drainage reduce impact.',
      'Evacuation and relief camps save lives.',
      // Extra details
      'Floods occur when water overflows onto normally dry land.',
      'Heavy rainfall, melting snow, or dam failure cause floods.',
      'Flash floods rise quickly and without warning.',
      'River floods occur from prolonged rain in catchment areas.',
      'Urban areas flood due to poor drainage.',
      'Floodwaters carry debris and hazardous materials.',
      'Floods spread waterborne diseases.',
      'They can erode fertile soil and farmlands.',
      'Warning systems use rainfall and river gauges.',
      'Building embankments and dams helps reduce flooding.',
    ],
    dos: [
      'Move to higher ground immediately.',
      'Listen to emergency alerts.',
      'Keep drinking water safe.',
      'Turn off electricity before leaving.',
      'Carry emergency supplies.',
      'Stay away from floodwaters.',
      'Help vulnerable people.',
      'Store valuables in waterproof bags.',
      'Keep livestock safe.',
      'Practice family evacuation plan.',
    ],
    donts: [
      'Don’t walk or swim in floodwater.',
      'Don’t drive in flooded areas.',
      'Don’t touch electrical equipment in water.',
      'Don’t drink contaminated water.',
      'Don’t block drainage systems.',
      'Don’t spread rumors.',
      'Don’t go near collapsed bridges.',
      'Don’t return home until safe.',
      'Don’t ignore official warnings.',
      'Don’t panic or delay evacuation.',
    ],
    quiz: { title: 'Flood Quiz', href: '#' },
    drills: { title: 'Flood Drill', href: '#' },
  },
  {
    id: 'wildfire',
  title: 'Wildfire',
    description: 'Protect yourself and others during wildfires.',
    plan: [
      'Create a defensible space around homes (clear dry grass/leaves).',
      'Avoid campfires near dry forests.',
      'Never throw cigarette butts in open.',
      'Plant fire-resistant trees near homes.',
      'Store water hoses and buckets.',
      'Educate children about wildfire dangers.',
      'Practice evacuation routes.',
      'Monitor wildfire alerts.',
      'Keep masks ready for smoke.',
      'Avoid outdoor activities during fire warnings.',
      'Clear chimneys and rooftops of dry debris.',
      'Keep fire extinguishers and water sprays.',
      'Maintain safe distance from forests in summer.',
      'Never burn garbage in forest areas.',
      'Coordinate with forest rangers.',
      'Report sparks or fires immediately.',
      'Prepare livestock evacuation plans.',
      'Keep important documents in fireproof bags.',
      'Do not return home until safe clearance.',
    ],
    recovery: [
      'Ensure all fires are completely extinguished.',
      'Watch for flare-ups in hotspots.',
      'Clear burnt debris safely.',
      'Provide medical aid for burns and smoke inhalation.',
      'Restore water supply and power lines.',
      'Replant trees and restore wildlife habitats.',
      'Support community shelters and housing needs.',
      'Build firebreaks and early warning systems for the future.',
    ],
    effects: [
      'Deaths and injuries from burns and smoke inhalation',
      'Destruction of homes, farms, and forests',
      'Loss of wildlife habitats and biodiversity',
      'Air pollution and respiratory illnesses',
      'Melting of power lines and communication breakdown',
      'Soil erosion and reduced fertility',
      'Disruption of transport and tourism',
      'Economic losses in forestry, housing, and farming',
      'Long-term ecological imbalance',
    ],
    know: [
      'Uncontrolled fire spreading in forests or grasslands.',
      'Fueled by dry vegetation and strong winds.',
      'Starts naturally (lightning) or by human activity.',
      'Spreads quickly and is hard to stop.',
      'Produces smoke harmful to health.',
      'Destroys wildlife habitats.',
      'Threatens homes near forests.',
      'Firefighters use water, firebreaks, and chemicals.',
      'Can spread for days or weeks.',
      'Climate change increases wildfire risks.',
      // Extra details
      'Wildfires spread rapidly in dry forests and grasslands.',
      'They can be caused by lightning, human activity, or sparks.',
      'Fire spreads faster uphill due to wind and slope.',
      'Wildfires release large amounts of carbon dioxide.',
      'Controlled burns help prevent larger fires.',
      'Animals flee or perish during wildfires.',
      'Wildfire smoke can travel thousands of miles.',
      'Firefighters use firebreaks to contain blazes.',
      'Climate change is increasing wildfire frequency.',
      'Some plant species depend on fire to release seeds.',
    ],
    dos: [
      'Evacuate immediately when told.',
      'Keep emergency kit and masks ready.',
      'Wet cloth to cover nose and mouth.',
      'Wear fire-resistant or cotton clothes.',
      'Keep vehicles fueled for evacuation.',
      'Follow official evacuation routes.',
      'Stay indoors if fire is far but air quality is poor.',
      'Remove dry leaves/combustibles from surroundings.',
      'Help neighbors in need.',
      'Report new fires to authorities.',
    ],
    donts: [
      'Don’t stay behind to protect property.',
      'Don’t re-enter burned areas.',
      'Don’t light outdoor fires during dry seasons.',
      'Don’t use elevators during evacuation.',
      'Don’t block evacuation roads.',
      'Don’t breathe smoke directly.',
      'Don’t spread unverified information.',
      'Don’t waste time gathering belongings.',
      'Don’t leave pets behind.',
      'Don’t ignore fire alarms or alerts.',
    ],
    quiz: { title: 'Wildfire Quiz', href: '#' },
    drills: { title: 'Wildfire Drill', href: '#' },
  },
  {
    id: 'hurricane',
    title: 'Hurricane / Cyclone',
    description: 'Prepare for and stay safe during hurricanes or cyclones.',
    plan: [
      'Understand cyclone alert colors (blue, yellow, red).',
      'Keep essentials packed (food, water, torch, documents).',
      'Stay updated with government warnings.',
      'Reinforce doors, windows, and rooftops.',
      'Secure outdoor objects (tin sheets, bikes, tanks).',
      'Identify nearest cyclone shelters.',
      'Plan evacuation routes with family.',
      'Store clean water in advance.',
      'Keep battery-operated radio and torches.',
      'Avoid windows during cyclone winds.',
      'Ensure school safety and temporary closure after red alerts.',
      'Disconnect electrical appliances.',
      'Keep livestock secured in safe shelters.',
      'Do not go out until official “all clear” signal.',
      'Store medicines for chronic patients.',
      'Practice cyclone drills with children.',
      'Share cyclone preparedness tips in community.',
      'Keep important contact numbers handy.',
      'Prepare for post-cyclone flooding and disease risks.',
    ],
    recovery: [
      'Stay in safe shelter until officials declare it’s over.',
      'Avoid fallen power lines and flooded areas.',
      'Clear debris blocking roads and homes.',
      'Use safe, clean water and food supplies.',
      'Repair damaged roofs, windows, and walls.',
      'Rebuild houses with cyclone-resistant designs.',
      'Restore communication lines and community centers.',
      'Create safe evacuation routes for the future.',
    ],
    effects: [
      'Extremely strong winds causing deaths and injuries',
      'Uprooting of trees and destruction of vegetation',
      'Storm surges flooding coastal areas',
      'Destruction of homes, offices, and schools',
      'Collapse of power and communication systems',
      'Contamination of freshwater sources with seawater',
      'Loss of fishing boats and coastal industries',
      'Economic slowdown in affected regions',
      'Mass displacement of coastal populations',
    ],
    know: [
      'Large rotating storm over warm ocean waters.',
      'Called cyclones in the Indian Ocean, typhoons in the Pacific.',
      'Winds exceed 119 km/h.',
      'Has an eye (calm center) and eye wall (strongest winds).',
      'Can be 500+ km wide.',
      'Brings heavy rainfall and storm surges.',
      'Causes floods, landslides, and destruction.',
      'Named storms tracked yearly by meteorologists.',
      'Form mostly during warm seasons.',
      'Evacuation orders often save lives.',
      // Extra details
      'Hurricanes are tropical cyclones with strong rotating winds.',
      'They form over warm ocean waters (above 26°C / 79°F).',
      'The Saffir-Simpson scale rates hurricanes (Category 1–5).',
      'The calm center is called the "eye" of the storm.',
      'The "eyewall" has the strongest winds and rain.',
      'Storm surges cause the most flooding and deaths.',
      'Hurricanes weaken once they move over land.',
      'Atlantic hurricanes are tracked by NOAA.',
      'Cyclones in the Indian Ocean affect millions yearly.',
      'Climate change is increasing hurricane intensity.',
    ],
    dos: [
      'Stay indoors during the storm.',
      'Board up windows and doors.',
      'Keep emergency kit ready.',
      'Charge all electronic devices.',
      'Follow evacuation orders.',
      'Move to higher ground in case of flooding.',
      'Stay tuned to official updates.',
      'Secure outdoor items (furniture, plants).',
      'Store drinking water safely.',
      'Help neighbors, especially elderly.',
    ],
    donts: [
      'Don’t go outside during the eye of the storm.',
      'Don’t ignore evacuation orders.',
      'Don’t use candles (fire hazard).',
      'Don’t drive in flooded areas.',
      'Don’t leave pets unattended.',
      'Don’t spread panic.',
      'Don’t rely on rumors or social media only.',
      'Don’t swim in stormy seas.',
      'Don’t return until safe.',
      'Don’t use contaminated water.',
    ],
    quiz: { title: 'Hurricane Quiz', href: '#'},
    drills: { title: 'Hurricane Drill', href: '#'},
  },
  {
    id: 'tsunami',
  title: 'Tsunami',
    description: 'Be ready for coastal tsunamis.',
    plan: [
      'Check if home/work/school is in tsunami hazard zone.',
      'Know the elevation of your location.',
      'Identify evacuation routes to higher ground.',
      'Practice evacuation with family.',
      'Learn your school’s tsunami evacuation plan.',
      'Monitor radio/TV for tsunami alerts.',
      'Join community awareness drills.',
      'Store emergency kits at home and school.',
      'Do not wait for official instructions if the ground shakes near the coast—move immediately.',
      'Teach children “earthquake + ocean retreat = tsunami.”',
      'Know multiple safe routes (not just one).',
      'Secure valuables in waterproof bags.',
      'Keep pets included in evacuation plans.',
      'Teach children to follow teachers during evacuation.',
      'Avoid going near shore to watch waves.',
      'Keep vehicles fuelled in hazard areas.',
      'Talk to insurance agents about disaster coverage.',
      'Review flood and earthquake safety with tsunami planning.',
      'Return home only when authorities declare it safe.',
    ],
    recovery: [
      'Stay inland until authorities confirm it’s safe.',
      'Search and rescue survivors with trained help.',
      'Clean contaminated water sources.',
      'Remove debris from roads, ports, and homes.',
      'Treat injuries and provide mental health support.',
      'Rebuild homes on higher ground when possible.',
      'Install tsunami warning systems and evacuation signs.',
      'Strengthen coastal barriers with mangroves/sea walls.',
    ],
    effects: [
      'Huge loss of human lives and injuries',
      'Entire coastal towns submerged or destroyed',
      'Saltwater contamination of farmland and water sources',
      'Collapse of transportation, ports, and harbors',
      'Massive displacement of populations',
      'Loss of marine biodiversity and ecosystems',
      'Spread of diseases due to stagnant water and corpses',
      'Economic losses from destroyed industries and tourism',
    ],
    know: [
      'Series of giant ocean waves.',
      'Caused by undersea earthquakes, volcanoes, or landslides.',
      'Waves travel very fast across oceans.',
      'Height increases near the coast (harbor wave).',
      'Can flood coastal cities and villages.',
      'Time between waves may range from minutes to an hour.',
      'First wave is not always the largest.',
      'Tsunami warnings are issued after major quakes.',
      'People must move to higher ground immediately.',
      'No link to daily tides (not tidal waves).',
      // Extra details
      'Tsunamis are caused by undersea earthquakes, landslides, or volcanic eruptions.',
      'They can travel at speeds over 500 mph (800 km/h).',
      'In deep water, tsunamis are barely noticeable.',
      'Wave heights increase drastically near the shore.',
      'They can inundate coastal areas within minutes of arrival.',
      'A receding ocean shoreline can signal an approaching tsunami.',
      'Tsunami waves can travel across entire oceans.',
      'The Indian Ocean tsunami (2004) killed over 200,000 people.',
      'Warning systems rely on ocean buoys and seismographs.',
      'Coastal mangroves and reefs help reduce tsunami impacts.',
    ],
    dos: [
      'Move to higher ground immediately after shaking.',
      'Listen to tsunami warnings and alerts.',
      'Follow official evacuation routes.',
      'Carry emergency supplies.',
      'Help children and elderly during evacuation.',
      'Stay away from coastal areas until declared safe.',
      'Keep important documents in waterproof bags.',
      'Practice tsunami evacuation drills.',
      'Stay tuned to official updates.',
      'Stay calm and assist others.',
    ],
    donts: [
      'Don’t wait to see the waves.',
      'Don’t go back to shore until cleared.',
      'Don’t spread rumors or panic.',
      'Don’t swim in strong currents.',
      'Don’t block evacuation paths.',
      'Don’t underestimate small tremors near the coast.',
      'Don’t stay in low-lying areas.',
      'Don’t use vehicles if roads are jammed.',
      'Don’t drink flood-contaminated water.',
      'Don’t ignore repeated warnings.',
    ],
    quiz: { title: 'Tsunami Quiz', href: '#'},
    drills: { title: 'Tsunami Drill', href: '#'},
  },
  {
    id: 'pandemic',
  title: 'Pandemic',
    description: 'Stay healthy during widespread disease outbreaks.',
    dos: [
      'Wash hands regularly',
      'Wear masks in crowded places',
      'Follow health guidelines',
    ],
    donts: [
      'Don’t ignore symptoms',
      'Don’t spread misinformation',
      'Don’t neglect vaccination',
    ],
    quiz: { title: 'Pandemic Quiz', href: '#'},
    drills: { title: 'Pandemic Drill', href: '#'},
  },
  {
    id: 'heatwave',
    title: 'Heatwave Readiness',
    description: 'Stay cool and safe during extreme heat.',
    dos: [
      'Drink plenty of water',
      'Stay in the shade or indoors',
      'Wear light clothing',
    ],
    donts: [
      'Don’t leave kids or pets in cars',
      'Don’t overexert during peak heat',
      'Don’t ignore signs of heatstroke',
    ],
    quiz: { title: 'Heatwave Quiz', href: '#'},
    drills: { title: 'Heatwave Drill', href: '#'},
  },
  {
    id: 'landslide',
  title: 'Landslide',
    description: 'Know what to do in landslide-prone areas.',
    plan: [
      'Make a family communication and evacuation plan.',
      'Save critical facility numbers (police, fire, hospital).',
      'Avoid unplanned construction on unstable slopes.',
      'Plant trees and vegetation to stabilize soil.',
      'Drain rainwater properly away from slopes.',
      'Do not cut steep slopes for roads without protection.',
      'Avoid settling at the base of steep hills.',
      'Listen to landslide alerts by local authorities.',
      'Watch for cracks on slopes after heavy rains.',
      'Never block natural water drainage.',
      'Prepare go-kits before traveling to hilly areas.',
      'Avoid camping on valley floors.',
      'Learn safe spots in mountain areas (open grounds).',
      'Carry emergency radios while hiking.',
      'Train children on emergency landslide drills.',
      'Avoid construction near rivers prone to erosion.',
      'Cooperate with community disaster management teams.',
      'Keep slope areas free of loose stones/debris.',
      'Stay indoors during heavy rainfall in risk zones.',
    ],
    recovery: [
      'Stay away from the landslide site; secondary slides may occur.',
      'Report damaged roads, railways, and utilities to authorities.',
      'Check for trapped people and animals; help if safe.',
      'Reconnect essential services (electricity, water, telecom) safely.',
      'Remove debris carefully without triggering further slides.',
      'Plant vegetation to stabilize soil.',
      'Strengthen slopes with retaining walls.',
      'Avoid rebuilding in high-risk areas.',
    ],
    effects: [
      'Sudden burial of people, homes, and roads',
      'Blockage of rivers, causing flash floods',
      'Loss of fertile land and vegetation',
      'Disruption of transport and communication',
      'Damage to power lines and pipelines',
      'Loss of human and animal lives',
      'Destruction of tourism and livelihoods in hilly areas',
      'Long-term soil instability and erosion',
    ],
    know: [
      'Downward movement of rocks, soil, or debris.',
      'Triggered by earthquakes, rainfall, or human activity.',
      'Common in hilly and mountain areas.',
      'Blocks roads, rivers, and railways.',
      'Can bury houses and vehicles.',
      'Often sudden and fast-moving.',
      'Deforestation increases risk.',
      'Avalanches are similar but with snow/ice.',
      'Warning signs: cracks in ground, tilting trees.',
      'Drainage and slope control can reduce risks.',
      // Extra details
      'Landslides are sudden downhill movements of rock and soil.',
      'Triggered by earthquakes, rain, or volcanic activity.',
      'Slope steepness increases landslide risk.',
      'Landslides destroy roads, bridges, and homes.',
      'Warning signs include tilted trees and cracked ground.',
      'Landslides can block rivers and form dams.',
      'Mudflows are fast-moving landslides with water.',
      'Engineering solutions include retaining walls and drainage.',
      'Deforestation increases landslide risk.',
      'Landslide-prone areas are mapped for safety planning.',
    ],
    dos: [
      'Stay alert in hilly/rain-prone areas.',
      'Move away from landslide paths quickly.',
      'Follow official evacuation orders.',
      'Keep emergency kit ready.',
      'Report early warning signs (cracks, tilting trees).',
      'Stay tuned to weather reports.',
      'Help others evacuate.',
      'Keep drainage systems clear.',
      'Carry important documents in waterproof bags.',
      'Move to safe zones immediately.',
    ],
    donts: [
      'Don’t build houses near steep slopes.',
      'Don’t ignore warning signs.',
      'Don’t return until declared safe.',
      'Don’t block natural water flow.',
      'Don’t walk near riverbanks during heavy rain.',
      'Don’t park vehicles near slopes.',
      'Don’t underestimate small landslides.',
      'Don’t spread panic.',
      'Don’t neglect community evacuation plans.',
      'Don’t stay inside unstable buildings.',
    ],
    quiz: { title: 'Landslide Quiz', href: '#'},
    drills: { title: 'Landslide Drill', href: '#'},
  },
  {
    id: 'volcano',
  title: 'Volcano',
    description: 'Protect yourself from volcanic ash and hazards.',
    recovery: [
      'Stay indoors if ash is falling; wear masks outdoors.',
      'Clean roofs frequently to prevent ash collapse.',
      'Dispose of ash safely (don’t dump in drains).',
      'Avoid streams and rivers that may carry volcanic mudflows (lahars).',
      'Restore farmland by removing ash or mixing it with soil.',
      'Repair damaged water sources.',
      'Provide shelters and medical support for displaced people.',
      'Rebuild with evacuation plans in high-risk zones.',
    ],
    know: [
      'An opening in Earth’s crust where lava, ash, and gases erupt.',
      'Formed at tectonic plate boundaries or hotspots.',
      'Lava flows can destroy property and land.',
      'Ash clouds affect air travel and breathing.',
      'Explosions can be sudden and powerful.',
      'Can cause pyroclastic flows (hot gases + rock).',
      'Sometimes triggers landslides or tsunamis.',
      'Volcanoes may stay dormant for centuries.',
      'Fertile soil often forms around volcanoes.',
      'Scientists monitor gases and tremors to give warnings.',
      // Extra details
      'Volcanoes are openings in the Earth’s crust where magma escapes.',
      'They can form new landmasses over time.',
      'Volcanic eruptions release gases like sulfur dioxide and carbon dioxide.',
      'Ash clouds can disrupt air travel for weeks.',
      'Lava flows move slowly but cause long-term destruction.',
      'Pyroclastic flows are fast and deadly.',
      'Volcanoes are classified as active, dormant, or extinct.',
      'Volcanic soils are rich in minerals and very fertile.',
      'Supervolcanoes can impact global climate.',
      'Monitoring volcanic tremors helps predict eruptions.',
    ],
    dos: [
      'Stay indoors to avoid ash.',
      'Use masks or cloth to cover your nose and mouth.',
      'Keep windows and doors closed.',
      'Follow official evacuation orders.',
      'Wear long-sleeved clothing to protect skin.',
      'Stay tuned to radio or official updates.',
      'Prepare emergency kits with goggles and water.',
      'Keep vehicles indoors to avoid ash damage.',
      'Help vulnerable people (elderly, kids).',
      'Stay away from rivers (can carry lava or ash).',
    ],
    donts: [
      'Don’t go near lava flows or craters.',
      'Don’t breathe volcanic ash directly.',
      'Don’t drive unless absolutely necessary.',
      'Don’t ignore evacuation instructions.',
      'Don’t drink ash-contaminated water.',
      'Don’t panic or rush evacuation.',
      'Don’t leave pets behind.',
      'Don’t use contact lenses (ash irritation).',
      'Don’t stand on rooftops with heavy ash (collapse risk).',
      'Don’t spread unverified information.',
    ],
    quiz: { title: 'Volcano Quiz', href: '#'},
    drills: { title: 'Volcano Drill', href: '#'},
    effects: [
      'Lava flows burning everything in their path',
      'Deaths and injuries from hot gases, ash, and rocks',
      'Collapse of buildings due to ash accumulation',
      'Contamination of rivers and lakes with ash/lava',
      'Disruption of air travel (volcanic ash clouds)',
      'Long-term respiratory diseases (from ash inhalation)',
      'Destruction of farmlands and forests',
      'Economic losses in agriculture, tourism, and housing',
    ],
  },
  {
    id: 'tornado',
  title: 'Tornado',
    description: 'Know where to shelter and how to stay safe during tornadoes.',
    plan: [
      'Learn difference between tornado watch & warning.',
      'Identify safe spots (basement, storm shelter).',
      'Avoid windows during tornado warnings.',
      'Practice duck-and-cover drills.',
      'Keep helmets to protect from flying debris.',
      'Store emergency supplies underground.',
      'Keep radio tuned to weather alerts.',
      'Avoid mobile homes during tornado.',
      'Anchor loose outdoor objects.',
      'Never attempt to outrun tornado in car.',
      'Teach children school tornado drills.',
      'Identify landmarks (sirens, shelters).',
      'Prepare flashlight, batteries, whistle.',
      'Avoid bridges/flyovers for shelter.',
      'Keep important contacts ready.',
      'Educate children not to panic.',
      'Have pets included in tornado plans.',
      'Avoid open grounds when sirens blow.',
      'Return home only when officials confirm safety.',
    ],
    recovery: [
      'Avoid damaged structures; they may collapse.',
      'Report downed power lines immediately.',
      'Check on neighbors, especially children and elderly.',
      'Collect and document debris damage.',
      'Repair homes with tornado-resistant designs (e.g., storm shelters).',
      'Restore water, power, and communication services.',
      'Provide counseling for trauma.',
      'Replant trees and vegetation to reduce wind impact in the future.',
    ],
    know: [
      'A violently rotating column of air touching the ground.',
      'Connected to thunderstorm clouds.',
      'Looks like a funnel-shaped cloud.',
      'Wind speeds can exceed 300 km/h.',
      'Can destroy homes and uproot trees.',
      'Usually last for a few minutes, but very destructive.',
      'Measured on the Enhanced Fujita (EF) scale.',
      'Form mostly in flat areas with warm, moist air.',
      'Can carry debris far away.',
      'Storm shelters provide the best protection.',
      // Extra details
      'Tornadoes form from severe thunderstorms.',
      'They are most common in "Tornado Alley" in the USA.',
      'Fujita scale rates tornadoes from EF0 to EF5.',
      'Tornadoes can appear transparent until they collect debris.',
      'Multiple tornadoes can form in a single storm system.',
      'They usually move southwest to northeast.',
      'Tornadoes last from a few minutes to over an hour.',
      'The strongest winds exceed 300 mph (480 km/h).',
      'They can uproot trees, cars, and buildings.',
      'Tornado warning systems use Doppler radar.',
    ],
    dos: [
      'Go to a basement or storm shelter.',
      'Stay in an interior room with no windows.',
      'Protect your head with arms or a helmet.',
      'Keep a radio for weather alerts.',
      'Cover yourself with blankets or a mattress.',
      'Stay away from doors and windows.',
      'If outdoors, find a low ditch or depression.',
      'Keep emergency supplies ready.',
      'Secure heavy objects at home.',
      'Practice tornado drills with family.',
    ],
    donts: [
      'Don’t stay in mobile homes.',
      'Don’t try to outrun a tornado in a car.',
      'Don’t open windows to “equalize pressure.”',
      'Don’t stand near glass or doors.',
      'Don’t ignore sirens or warnings.',
      'Don’t use elevators.',
      'Don’t waste time collecting belongings.',
      'Don’t take shelter under bridges.',
      'Don’t go outside to “watch” the tornado.',
      'Don’t panic—stay low and covered.',
    ],
    quiz: { title: 'Tornado Quiz', href: '#'},
    drills: { title: 'Tornado Drill', href: '#'},
    effects: [
      'Destruction of homes, farms, and buildings',
      'Flying debris causing injuries and deaths',
      'Uprooting of trees and vegetation',
      'Disruption of transport and power supply',
      'Economic damage to industries and agriculture',
      'Psychological trauma for survivors',
      'Livestock and pet deaths',
      'Temporary loss of communication networks',
    ],
  },
  {
    id: 'drought',
  title: 'Drought',
    description: 'Conserve water and adapt during droughts.',
    plan: [
      'Educate family on water conservation.',
      'Fix leaking taps/pipes.',
      'Store water safely.',
      'Avoid wasteful irrigation.',
      'Use drip irrigation for gardens/crops.',
      'Collect rainwater (rooftop harvesting).',
      'Grow drought-resistant crops.',
      'Plant trees to increase soil moisture.',
      'Avoid cutting green cover.',
      'Keep emergency food storage.',
      'Teach children about saving water.',
      'Use water-efficient appliances.',
      'Plan livestock water needs.',
      'Reuse greywater for plants.',
      'Avoid groundwater over-extraction.',
      'Keep water tankers ready for emergencies.',
      'Follow local water-use advisories.',
      'Share water conservation practices in community.',
      'Ensure hygiene even during water shortages.',
    ],
    recovery: [
      'Provide immediate drinking water and food supplies.',
      'Set up community water-sharing systems.',
      'Restore water sources (wells, reservoirs, rainwater harvesting).',
      'Support farmers with drought-resistant seeds.',
      'Implement irrigation and soil conservation methods.',
      'Monitor and ration water use.',
      'Launch reforestation drives to restore ecosystem balance.',
      'Create long-term drought management plans.',
    ],
    know: [
      'Long period of below-normal rainfall.',
      'Leads to water shortage for people, crops, and animals.',
      'Can last months or years.',
      'Causes crop failure and food shortage.',
      'Increases risk of wildfires.',
      'Reduces river and groundwater levels.',
      'Affects electricity generation in dams.',
      'People migrate from affected areas.',
      'Relief measures include water-saving and tankers.',
      'Can be predicted with rainfall data.',
      // Extra details
      'Droughts result from prolonged periods of low rainfall.',
      'They affect drinking water, agriculture, and power supply.',
      'Drought severity is measured using rainfall and soil moisture data.',
      'Droughts cause crop failures and food shortages.',
      'They increase risk of wildfires.',
      'Groundwater levels decline during droughts.',
      'Droughts can last months or years.',
      'Dust storms are common in drought-stricken areas.',
      'Drought-related famines are a global humanitarian concern.',
      'Water rationing and rainwater harvesting help reduce impact.',
    ],
    dos: [
      'Conserve water daily.',
      'Collect rainwater if possible.',
      'Grow drought-resistant plants.',
      'Take shorter showers.',
      'Use water-efficient appliances.',
      'Reuse greywater for plants.',
      'Educate community on water conservation.',
      'Store drinking water in clean containers.',
      'Support reforestation efforts.',
      'Follow government water usage rules.',
    ],
    donts: [
      'Don’t waste water unnecessarily.',
      'Don’t wash vehicles frequently.',
      'Don’t over-irrigate fields.',
      'Don’t leave taps running.',
      'Don’t ignore leaks at home.',
      'Don’t use drinking water for non-essential tasks.',
      'Don’t pollute available water sources.',
      'Don’t panic-buy bottled water.',
      'Don’t cut down trees.',
      'Don’t ignore official restrictions.',
    ],
    quiz: { title: 'Drought Quiz', href: '#'},
    drills: { title: 'Drought Drill', href: '#'},
    effects: [
      'Severe shortage of drinking water',
      'Crop failures and loss of livestock',
      'Starvation and malnutrition',
      'Mass migration of rural populations',
      'Drying of rivers, lakes, and groundwater',
      'Spread of poverty and unemployment',
      'Increase in wildfires due to dry conditions',
      'Long-term soil degradation and desertification',
      'Economic collapse in agriculture-based areas',
    ],
  },
  {
    id: 'fire',
  title: 'Fire',
    description: 'Know how to prevent and respond to home and building fires.',
    plan: [
      'Install smoke detectors in kitchens and bedrooms.',
      'Keep fire extinguishers at accessible spots.',
      'Educate family on using extinguishers.',
      'Lock matches/lighters away from children.',
      'Replace faulty or sparking appliances.',
      'Avoid overloading electrical circuits.',
      'Do not leave cooking unattended.',
      'Practice “Stop, Drop, Roll” with children.',
      'Identify fire exits at home and school.',
      'Keep escape ladders in multi-storey houses.',
      'Plan meeting points after evacuation.',
      'Never block fire exits.',
      'Keep emergency numbers near the phone.',
      'Practice fire drills regularly.',
      'Teach children not to hide during fires.',
      'Store flammable liquids safely.',
      'Maintain LPG connections properly.',
      'Switch off power during fire emergencies.',
      'Cooperate with fire brigade during rescue.',
    ],
    dos: [
      'Install smoke alarms on every level of your home and test monthly.',
      'Plan and practice a home fire escape plan with two exits from each room.',
      'Keep matches, lighters, and candles out of children’s reach.',
      'Turn off gas and electrical appliances when not in use.',
      'Use a fire extinguisher only if trained and the fire is small.',
      'Crawl low under smoke and close doors behind you when escaping.',
      'Stop, Drop, and Roll if your clothes catch fire.',
      'Keep flammable items at least 3 feet away from heaters.',
      'Call emergency services from a safe place once outside.',
      'Meet at a designated safe spot outside—never re-enter a burning building.',
    ],
    donts: [
      'Don’t overload electrical outlets or use damaged cords.',
      'Don’t leave cooking unattended—stay in the kitchen while frying or grilling.',
      'Don’t use elevators during a fire evacuation.',
      'Don’t open hot doors—use the back of your hand to check for heat.',
      'Don’t block exits, hallways, or stairwells with furniture or storage.',
      'Don’t store gasoline or flammables indoors without proper containers.',
      'Don’t hide during a fire—get out and stay out.',
      'Don’t return for belongings or pets once you’ve exited.',
      'Don’t ignore chirping smoke alarms—replace batteries immediately.',
      'Don’t attempt to fight large or spreading fires—evacuate at once.',
    ],
    quiz: { title: 'Fire Safety Quiz', href: '#' },
    drills: { title: 'Home Fire Drill', href: '#' },
  },
  {
    id: 'thunderstorm',
    title: 'Thunderstorm & Lightning',
    description: 'Stay safe from lightning, strong winds, and heavy rain.',
    dos: [
      'Seek shelter indoors or in a hard-topped vehicle when thunder roars.',
      'Unplug sensitive electronics to protect from surges.',
      'Stay away from windows and doors; close curtains or blinds.',
      'Avoid using wired electronics and plumbing during storms.',
      'If outside with no shelter, crouch low on the balls of your feet—minimize contact with the ground.',
      'Secure loose outdoor items that can blow away.',
      'Monitor official weather alerts and wait 30 minutes after last thunder before resuming activities.',
      'If flooding is possible, move to higher ground.',
      'Teach kids the 30/30 rule: if time between lightning and thunder is < 30 seconds, go indoors.',
      'Keep a flashlight and emergency kit ready for power outages.',
    ],
    donts: [
      'Don’t shelter under isolated trees or small open structures.',
      'Don’t lie flat on the ground during lightning.',
      'Don’t swim, fish, or boat—get out of the water immediately.',
      'Don’t touch metal fences, poles, or bicycles during lightning.',
      'Don’t drive through flooded roads—turn around, don’t drown.',
      'Don’t use corded phones; prefer mobile on battery power.',
      'Don’t stand near windows—flying debris and glass can injure.',
      'Don’t ignore watches and warnings from authorities.',
      'Don’t leave pets outside during severe weather.',
      'Don’t relight candles or use open flames if gas leaks are suspected.',
    ],
    quiz: { title: 'Thunderstorm Quiz', href: '#' },
    drills: { title: 'Lightning Safety Drill', href: '#' },
  },
];

export default disastersData;
